### ISSUE TITLE
Understanding the Algorithm about the nearby cars

### ISSUE THREAD

**Issue by Gan-Song-CU** [Atcold/pytorch-PPUU#64]
In building the forward model, as in your paper said, the surrounding cars will not be modeled as human-like behaves, but just follow their trajectories in the dataset. Then why in the simulated scenarios from the forward model from the same initial state, the surrounding cars' trajectories are different in different scenarios, should they be all the same since we just follow their trajectories in the dataset?

**Comment by Atcold** [comment]
1. The forward model learns how the surrounding cars behave.
2. We learn their future locations given their past locations and velocities, the traffic configuration, and the lane demarcations.
3. We use a latent variable to capture a variety of different behaviours (rather than averaging them all out).
4. When we "play" the forward model, and sample random latent, we end up with novel behaviour for the neighbouring vehicles.
